---
- name: Installing ES cluster
  hosts: aws
  become: yes
  become_user: root
  gather_facts: no
  vars:
    - number_of_nodes: 3
  tasks:

    - name: Disable vm swappiness
      sysctl:
        name: vm.swappiness
        value: 0
        state: present

    - name: Configuring the vm.max_map_count
      sysctl:
        name: vm.max_map_count
        value: 262144
        state: present

    - name: Copying ES configuration file onto target
      copy:
        src: elasticsearch/
        dest: /data/elasticsearch/
        mode: '777'


    - name: Configuring the master node with ES, Logstash and Kibana. THIS MIGHT TAKE A WHILE...
      docker_container:
        name: "master_node"
        image: sebp/elk
        networks:
          - name: "es_network"
        ports:
          - 5601:5601
          - 9200:9200
          - 9300:9300
          - 5044:5044
        ulimits: nofile:65536:65536
        env:
          LOGSTASH_START: 0
          ELASTICSEARCH_START: 1
          KIBANA_START: 1
          ES_CONNECT_RETRY: 300
        volumes:
          - /data/elasticsearch/:/etc/elasticsearch


    - name: Configuring 3 worker nodes with ES and Logstash
      docker_container:
        name: "node{{item}}"
        image: sebp/elk
        networks:
          - name: "es_network"
        published_ports: all
        ulimits: nofile:65536:65536
        env:
          LOGSTASH_START: 1
          ELASTICSEARCH_START: 1
          KIBANA_START: 0
          ES_CONNECT_RETRY: 300
        volumes:
          - /data/elasticsearch/:/etc/elasticsearch
      with_sequence: count={{ number_of_nodes }}



