---
- name: Create a Deployment from running servers
  hosts: aws
  become: yes
  become_user: root
  tasks:

    - name: Copying Deployments to directory
      copy:
        src: kubernetes/deployment.yml
        dest: /tmp
        mode: '777'

    - name: Create ELK deployment
      k8s:
        state: present
        src: /tmp/deployment.yml
